source 'https://rubygems.org'

gemspec

group :development, :local, :test do
  gem 'rspec'
  gem 'json'
  gem 'concurrent-ruby-ext'
  gem 'faraday'
  gem 'faraday-cookie_jar'
  gem 'ms_rest', path: '../ms-rest'  # use this for local development
end